"""Adding posts table.

Revision ID: 8b54bc3aed7d
Revises: 8c274ed5ea87
Create Date: 2025-05-21 21:42:14.811722

"""
from alembic import op
import sqlalchemy as sa
from lib.util_sqlalchemy import AwareDateTime


# revision identifiers, used by Alembic.
revision = '8b54bc3aed7d'
down_revision = '8c274ed5ea87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('markdown_content', sa.Text(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created_on', AwareDateTime(), nullable=True),
    sa.Column('updated_on', AwareDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'posts', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='unique')
    op.drop_table('posts')
    # ### end Alembic commands ###
