"""Adding admin table.

Revision ID: 8c274ed5ea87
Revises:
Create Date: 2025-05-19 16:39:21.684022

"""

import sqlalchemy as sa
from alembic import op

from lib.util_sqlalchemy import AwareDateTime

# revision identifiers, used by Alembic.
revision = "8c274ed5ea87"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("mfa_secret", sa.String(length=32), nullable=True),
        sa.Column("created_on", AwareDateTime(), nullable=True),
        sa.Column("updated_on", AwareDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("admin_users")
    # ### end Alembic commands ###
